### ISSUE TITLE
Request timed out

### ISSUE THREAD

**Issue by benjamin-wilson** [ecadlabs/taquito#1012]
**Description**
When invoking a contract method, more often than not it times out.

**Steps To Reproduce**
1. Setup taquito in a nodejs environment
2. Set giganode provider
```
        this.Tezos = new TezosToolkit('https://mainnet-tezos.giganode.io');
        this.Tezos.setProvider({
            signer,
            config: { confirmationPollingIntervalSecond: 5 }
        });

```
3. Invoke contract method
```
const request = contract.methods.my_method(
                ..args
            );
const operation = await request.send({ amount: 0, storageLimit: 310 });
```
4. Wait for error
```
Error: Request timed out after: 30000ms
    at XMLHttpRequest.ontimeout (C:\Repos\regmax-tezos-back-end\node_modules\@taquito\http-utils\src\taquito-http-utils.ts:144:16)
    at XMLHttpRequest.dispatchEvent (C:\Repos\regmax-tezos-back-end\node_modules\xhr2-cookies\xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._dispatchProgress (C:\Repos\regmax-tezos-back-end\node_modules\xhr2-cookies\xml-http-request.ts:390:8)
    at XMLHttpRequest._onHttpTimeout (C:\Repos\regmax-tezos-back-end\node_modules\xhr2-cookies\xml-http-request.ts:370:8)
    at ClientRequest.<anonymous> (C:\Repos\regmax-tezos-back-end\node_modules\xhr2-cookies\xml-http-request.ts:264:67)
```
**Expected behavior**
No timeout

**Desktop (please complete the following information):**
Node 14.16.0
"@taquito/beacon-wallet": "10.0.0",
"@taquito/michelson-encoder": "10.0.0",
"@taquito/signer": "10.0.0",
"@taquito/taquito": "10.0.0",
"@taquito/utils": "10.0.0",

**Additional context**
This is a persistent problem. Giganode status shows no issues. 
[https://tezos.giganode.io/](https://tezos.giganode.io/)

**Comment by roxaneletourneau** [comment]
Maybe related to https://github.com/ecadlabs/taquito/issues/751
