### ISSUE TITLE
Getting unhandled promise rejection errors

### ISSUE THREAD

**Issue by emchristiansen** [ecadlabs/taquito#1024]
I'm getting unhandled promise rejection errors when I use Taquito, even if I wrap all my code in a try / catch.
To me this indicates a promise is being created inside Taquito or one of its dependencies, and that promise isn't awaited and it doesn't have a `catch` clause.

I see them the most when sending transactions. Here's the text from one of them:
```
Error: Confirmation polling timed out
    at TapSubscriber._tapNext (/home/ericmartinchristiansen/code/taquito/packages/taquito/dist/taquito.umd.js:1426:31)
    at TapSubscriber._next (/home/ericmartinchristiansen/code/taquito/packages/taquito/node_modules/rxjs/internal/operators/tap.js:59:27)
    at TapSubscriber.Subscriber.next (/home/ericmartinchristiansen/code/taquito/packages/taquito/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SwitchMapSubscriber.notifyNext (/home/ericmartinchristiansen/code/taquito/packages/taquito/node_modules/rxjs/internal/operators/switchMap.js:85:26)
    at SimpleInnerSubscriber._next (/home/ericmartinchristiansen/code/taquito/packages/taquito/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (/home/ericmartinchristiansen/code/taquito/packages/taquito/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MapToSubscriber._next (/home/ericmartinchristiansen/code/taquito/packages/taquito/node_modules/rxjs/internal/operators/mapTo.js:38:26)
    at MapToSubscriber.Subscriber.next (/home/ericmartinchristiansen/code/taquito/packages/taquito/node_modules/rxjs/internal/Subscriber.js:66:18)
    at AsyncAction.dispatch (/home/ericmartinchristiansen/code/taquito/packages/taquito/node_modules/rxjs/internal/observable/timer.js:31:16)
    at AsyncAction._execute (/home/ericmartinchristiansen/code/taquito/packages/taquito/node_modules/rxjs/internal/scheduler/AsyncAction.js:71:18)
```

Are you sure you're catching all the errors in all your promises?

**Comment by Innkst** [comment]
This might be Granada-related. We see this issue more in our own integration tests. We will be investigating this soon.

**Comment by emchristiansen** [comment]
I think it's only indirectly Granada related.

I've noticed it happens when my tezos-node is pegging a core at 100%, which explains why the request times out - the node is busy doing other stuff. I think this is indirectly caused by Granada because something about Granada periodically causes tezos-node to use 100% cpu. But I think the underlying problem is Taquito is firing-and-forgetting Promises that don't have any error recovery logic.

**Comment by emchristiansen** [comment]
Have you tried using [`eslint-plugin-promise`](https://www.npmjs.com/package/eslint-plugin-promise)?
It's an eslint plugin that can [flag things that cause unhandled promise rejection errors](https://stackoverflow.com/questions/63069344/can-eslint-help-you-prevent-unhandled-promise-rejections).

**Comment by roxaneletourneau** [comment]
@emchristiansen does it happen with the contract or the wallet API?

**Comment by roxaneletourneau** [comment]
@emchristiansen  thanks for pointing this issue, it should be fixed by [PR-1051](https://github.com/ecadlabs/taquito/pull/1051)  in our next release (version 10.2.0). I will close the ticket but feel free to reopen it if you still get the behavior.
