### ISSUE TITLE
[Error deploying to flextesa sandbox] Error: TypeError: c.sort is not a function

### ISSUE THREAD

**Issue by system32uwu** [ecadlabs/taquito#1463]
**Description**

I'm trying to deploy a smart contract to a local node that uses Flextesa ithacabox (runs inside a docker container).

Dockerfile:

```
FROM oxheadalpha/flextesa:latest

WORKDIR /app

COPY . .

EXPOSE 20000
EXPOSE 80

ENV block_time=3

RUN ["ithacabox"] 
```

And I run the container like so:

`docker run -v $DIR/..:/app --rm --name gc-tezos --detach -p 20000:20000 -p 80:80 gc-tezos ithacabox start`

Then I have a deploy script:

```typescript
const contract = require("../../contracts/contract.json");
import { importKey } from "@taquito/signer";
import { TezosToolkit } from "@taquito/taquito";

export default async function () {
  const Tezos = new TezosToolkit("http://127.0.0.1:20000");
  await importKey(Tezos, process.env.PRIVATE_KEY);

  return await Tezos.contract
    .originate({
      code: contract,
      init: `(Pair"tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb"(Pair{}(Pair{}{})))`,
    })
    .then((originationOp) => {
      console.log(
        `Waiting for confirmation of origination for ${originationOp.contractAddress}...`
      );
      return originationOp.contract();
    })
    .then((contract) => {
      console.log(`Origination completed.`);
      return contract;
    })
    .catch((error) => console.log(`Error:`, error));
}
```

And I'm getting the following error:

```
Error: TypeError: c.sort is not a function
    at MichelCodecParser.<anonymous> (/home/system32uwu/Work/repos/golf-club-tezos/node_modules/@taquito/taquito/src/parser/michel-codec-parser.ts:81:34)
    at Generator.next (<anonymous>)
    at fulfilled (/home/system32uwu/Work/repos/golf-club-tezos/node_modules/@taquito/taquito/dist/taquito.umd.js:41:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Done in 2.32s.
``` 

I didn't see any documentation regarding deploying to a local node, but the example uses an ithacabox instance so that's what I'm using, 

**Steps To Reproduce**
1. Create a Docker container `cg-tezos`
1.1 File contents:

```
FROM oxheadalpha/flextesa:latest

WORKDIR /app

COPY . .

EXPOSE 20000
EXPOSE 80

ENV block_time=3

RUN ["ithacabox"]
``` 
1.2 Build the container with `docker build -t "gc-tezos" `.
1.3 Run the container

2. Deploy any smart contract 

```typescript
const contract = require("../../contracts/contract.json");
import { importKey } from "@taquito/signer";
import { TezosToolkit } from "@taquito/taquito";

export default async function () {
  const Tezos = new TezosToolkit("http://127.0.0.1:20000");
  await importKey(Tezos, process.env.PRIVATE_KEY);

  return await Tezos.contract
    .originate({
      code: contract,
      init: `(Pair"tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb"(Pair{}(Pair{}{})))`,
    })
    .then((originationOp) => {
      console.log(
        `Waiting for confirmation of origination for ${originationOp.contractAddress}...`
      );
      return originationOp.contract();
    })
    .then((contract) => {
      console.log(`Origination completed.`);
      return contract;
    })
    .catch((error) => console.log(`Error:`, error));
}
```

**Expected behavior**
I guess the contract should be deployed, using tezos-client to deploy it worked. Just to be sure I also tried with other smart contracts, and they all fail to deploy with the same error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora Linux 35

**Additional context**

When I first tried I didn't have port 80 exposed, with that I got the error 
```
Error: Error: Error: connect ECONNREFUSED 127.0.0.1:80
    at HttpBackend.<anonymous> (/home/system32uwu/Work/repos/golf-club-tezos/node_modules/@taquito/http-utils/src/taquito-http-utils.ts:144:15)
    at Generator.throw (<anonymous>)
    at rejected (/home/system32uwu/Work/repos/golf-club-tezos/node_modules/@taquito/http-utils/dist/taquito-http-utils.umd.js:30:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
What should be running on port 80?

**Comment by roxaneletourneau** [comment]
Hi @system32uwu 
From the error that you shared `Error: TypeError: c.sort is not a function at MichelCodecParser`, I think that the issue might not be related to the usage of flextesa, but rather an issue regarding the format of the contract code. 
Taquito sorts the `parameter`, `storage` and `code` properties of the contract code to be in the order expected by the RPC. In the current case, the error shows that it fails to achieve the sorting.
Can you share the contract code?

**Comment by system32uwu** [comment]
[Sure](https://gist.github.com/system32uwu/101a28b9177045433084ef90e220b07c), it was written in Archetype so I fear the issue is related to how archetype transpiles to Michelson.

Weird thing is I can totally deploy it using tezos-client and can interact with this contract from said CLI with no problems.

**Comment by roxaneletourneau** [comment]
The contract code seems to be correct. 
When deploying a contract where code is in Plain Michelson, the code property in the `originate` method needs to be a string. Can you validate if it is the case? Perhaps the format of "../../contracts/contract.json" (from the above snippet) is incorrect.

It should look like:
```
Tezos.contract.originate({
      code: `{
  storage (pair (address %admin) (pair (big_map %Memberships nat (pair (nat %member_id) (pair (string %token_uri) (pair (string %membership_hash) (pair (string %start_date) (string %end_date)))))) (pair (set %minters address) (big_map %metadata string bytes))));
  parameter (or (or (pair %mint_membership (nat %c_id) (pair (nat %c_member_id) (pair (string %c_token_uri) (pair (string %c_membership_hash) (pair (string %c_start_date) (string %c_end_date)))))) (address %add_minter)) (address %remove_minter));
  code { UNPAIR;
         DIP { UNPAIR 4 };
         [...]
             PAIR 4;
             NIL operation;
             PAIR } };
}`,
      init: `(Pair"tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb"(Pair{}(Pair{}{})))`,
    })
```

**Comment by hui-an-yang** [comment]
flextesa has not been updated since sep 2023, hence closing this
