### ISSUE TITLE
Taquito Integration Tests to Protocol J - contract-no-annotations-call-by-index-methodsObject.spec.ts - Signing Operation not authorized

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#1537]
On Monday net, the Test Suite

contract-no-annotations-call-by-index-methodsObject.spec.ts

fails with

```
    OperationNotAuthorized: Signing Operation not authorized

      156 |           throw new KeyNotFoundError(`Key not found: ${this.pkh}`, ex);
      157 |         } else if (ex.status === STATUS_CODE.FORBIDDEN) {
    > 158 |           throw new OperationNotAuthorizedError('Signing Operation not authorized', ex);
          |                 ^
      159 |         } else if (ex.status === STATUS_CODE.BAD_REQUEST) {
      160 |           throw new BadSigningDataError('Invalid data', ex, {
      161 |             bytes,

      at RemoteSigner.<anonymous> (../packages/taquito-remote-signer/src/taquito-remote-signer.ts:158:17)
          at Generator.throw (<anonymous>)
      at rejected (../packages/taquito-remote-signer/dist/taquito-remote-signer.umd.js:30:69)
```

**Comment by roxaneletourneau** [comment]
Failure from the keygen `"Not enough balance"`. The test is successful with a faucet key.
The amount spent by the test is higher than on another testnet because the cost_per_byte constant is erroneously set to 1000 instead of 250 on Mondaynet. cost_per_byte will be fixed in the next Mondaynet.
