### ISSUE TITLE
Taquito Integration Tests to Protocol J - contract-no-annotations-call-by-index.spec.ts - Signing Operation not authorized

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#1538]
On Monday net the test suite

contract-no-annotations-call-by-index.spec.ts

fails with

```
    OperationNotAuthorized: Signing Operation not authorized

      156 |           throw new KeyNotFoundError(`Key not found: ${this.pkh}`, ex);
      157 |         } else if (ex.status === STATUS_CODE.FORBIDDEN) {
    > 158 |           throw new OperationNotAuthorizedError('Signing Operation not authorized', ex);
          |                 ^
      159 |         } else if (ex.status === STATUS_CODE.BAD_REQUEST) {
      160 |           throw new BadSigningDataError('Invalid data', ex, {
      161 |             bytes,

      at RemoteSigner.<anonymous> (../packages/taquito-remote-signer/src/taquito-remote-signer.ts:158:17)
          at Generator.throw (<anonymous>)
      at rejected (../packages/taquito-remote-signer/dist/taquito-remote-signer.umd.js:30:69)
```

**Comment by roxaneletourneau** [comment]
Related to the keygen. By inspecting the log we see: `{"pool":"ephemeral-keys-mondaynet","rpc":"http://mondaynet.ecadinfra.com:8732","keyID":"fe998212-8b4f-4816-b79c-a6cc6f4b937c","pkh":"tz2E7qrYVhoS79oDn85dntbBBuqgC5joLEqT","reason":"Not enough balance","amountRequest":"-74912","amountAllowed":"40697434","level":"debug","message":"Signing request denied","timestamp":"2022-04-15T01:30:01.331Z"}
`
