### ISSUE TITLE
Taquito Integration Tests to Protocol J - contract-permits.spec.ts - storage_exhausted.operation

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#1539]
On Monday net

the test suite

contract-permits.spec.ts

fails with

```
    TezosOperationError: (temporary) proto.alpha.storage_exhausted.operation

      200 |     // Fail early in case of errors
      201 |     if (errors.length) {
    > 202 |       throw new TezosOperationError(errors, 'Error occurred during estimation');
          |             ^
      203 |     }
      204 |
      205 |     let numberOfOps = 1;

      at RPCEstimateProvider.<anonymous> (../packages/taquito/src/estimate/rpc-estimate-provider.ts:202:13)
      at fulfilled (../packages/taquito/dist/taquito.umd.js:41:62)
```

**Comment by roxaneletourneau** [comment]
It fails during the estimation of the following operation:
```
const mint_contract = await LocalTez1.contract.at(fa12_contract.address);
const mint = await mint_contract.methods.mint(bootstrap2_address, 10).send();
```
LocalTez1 only has a balance of 50000 mutez. During the estimation, the initial storage limit is set to the balance divided by the cost_per_byte. cost_per_byte is set to 1000 by mistake on Mondaynet instead of 250. So the initial storage limit is 50 which is lower than the storage the operation will need (~70).
