### ISSUE TITLE
Internal server Error when getBlock 2282564

### ISSUE THREAD

**Issue by thdung3** [ecadlabs/taquito#1552]
**Description**
When getBlock of 2282564. I got error "Internal server error". Could you help me take a look?

**Steps To Reproduce**

```
const { TezosToolkit } = require('@taquito/taquito');
const { RpcClient, RpcClientCache } = require('@taquito/rpc');
const rpcClient = new RpcClient('https://rpc.tzbeta.net/');
const tezos = new TezosToolkit(new RpcClientCache(rpcClient));


async function main() {
    const latestBlockHeight = await rpcClient.getBlock({ block: 'head' });
    const blockLevel = 2282564;
    const blockOffset = (blockLevel > 0) ? `genesis+${blockLevel}` : 'genesis';
    const blockInfo = await tezos.rpc.getBlock({ block: blockOffset })
    console.log('blockInfo:', blockInfo);

}

main()

```
Error: 
```
/Users/dungdang/Documents/test/wallet-test/node_modules/@taquito/http-utils/dist/taquito-http-utils.umd.js:469
                        throw new HttpResponseError(`Http error response: (${err.response.status}) ${errorData}`, err.response.status, err.response.statusText, errorData, url + this.serialize(query));
                              ^

HttpResponse: Http error response: (500) {"message":"Internal server error"}
    at HttpBackend.<anonymous> (/Users/dungdang/Documents/test/wallet-test/node_modules/@taquito/http-utils/dist/taquito-http-utils.umd.js:469:31)
    at Generator.throw (<anonymous>)
    at rejected (/Users/dungdang/Documents/test/wallet-test/node_modules/@taquito/http-utils/dist/taquito-http-utils.umd.js:31:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 500,
  statusText: 'Internal Server Error',
  body: '{"message":"Internal server error"}',
  url: 'https://rpc.tzbeta.net/chains/main/blocks/genesis+2282564'
}
```

**Comment by roxaneletourneau** [comment]
Hi @thdung3 
I think that older blocks are not always available on public RPC. It seems like the query you tried works with this one: https://mainnet-tezos.giganode.io
Here is a list of the different public RPC: https://tezostaquito.io/docs/rpc_nodes


<br class="Apple-interchange-newline">https://mainnet-tezos.giganode.io/
