### ISSUE TITLE
Integration test migrate J to K: several tests can no longer get '"balance_too_low"' expected error message

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#1752]
This is logged with Tezos as [#3373](https://gitlab.com/tezos/tezos/-/issues/3373),

the error message 'balance_too_low' is no longer being caught by some tests on fail and now different errors are being given.

example:
```
Estimate with very low balance using: https://kathmandunet.ecadinfra.com/ › Estimate transfer to regular address with insufficient balance

    expect(received).rejects.toEqual(expected) // deep equality

    Expected: ObjectContaining {"message": StringContaining "balance_too_low"}
    Received: [TezosOperationError: (temporary) proto.014-PtKathma.tez.subtraction_underflow]

      339 |       await expect(
      340 |         LowAmountTez.estimate.transfer({ to: await Tezos.signer.publicKeyHash(), mutez: true, amount: amt })
    > 341 |       ).rejects.toEqual(
          |                 ^
      342 |         expect.objectContaining({
      343 |           message: expect.stringContaining('balance_too_low'),
      344 |         }));

      at Object.toEqual (node_modules/expect/build/index.js:241:20)
      at contract-estimation-tests.spec.ts:341:17
      at fulfilled (contract-estimation-tests.spec.ts:5:58)
```

**Comment by michaelkernaghan** [comment]
Here you can see we can get an error with this form:
```
  errors: [
    {
      kind: 'temporary',
      id: 'proto.alpha.contract.balance_too_low',
      contract: 'tz1bwsEWCwSEXdRvnJxvegQZKeX5dj6oKEys',
      balance: '8999626',
      amount: '100000000'
    },
    {
      kind: 'temporary',
      id: 'proto.alpha.tez.subtraction_underflow',
      amounts: [Array]
    }
  ],
  errorDetails: 'Error occurred during estimation',
  id: 'proto.alpha.tez.subtraction_underflow',
  kind: 'temporary'
```
the test just needs to pick out blance_too_low from inside this return instead of from the bottom level where it used to be.

**Comment by roxaneletourneau** [comment]
I got it for the `subtraction_underflow` error, but I am reopening the issue until getting more details about the `empty_implicit_contract` error. 
See https://gitlab.com/tezos/tezos/-/issues/3373#note_1037903191

**Comment by michaelkernaghan** [comment]
this has been fixed.
