### ISSUE TITLE
Integration test migrate J to K: integration-tests rpc-nodes.spec.ts - in K protocol getTxRollupState gets 404

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#1765]
Integration test migrate J to K: integration-tests rpc-nodes.spec.ts - in K protocol getTxRollupState gets 404

run the integration tests:  npm run test:kathmandunet rpc-nodes.spec.ts

observe 

```
  ● Test calling all methods from RPC node: https://kathmandunet.ecadinfra.com › getTxRollupState

    HttpResponse: Http error response: (404)

      139 |         }
      140 |
    > 141 |         throw new HttpResponseError(
          |               ^
      142 |           `Http error response: (${err.response.status}) ${errorData}`,
      143 |           err.response.status as STATUS_CODE,
      144 |           err.response.statusText,

      at HttpBackend.<anonymous> (../packages/taquito-http-utils/src/taquito-http-utils.ts:141:15)
          at Generator.throw (<anonymous>)
      at rejected (../packages/taquito-http-utils/dist/taquito-http-utils.umd.js:30:69)
```

while on jakartanet the same test passes.

**Comment by michaelkernaghan** [comment]
it turns out that toru was sunsetted early in K protocol by mistake.

It will restarted and should start to work again.

**Comment by michaelkernaghan** [comment]
this has been fixed
