### ISSUE TITLE
forgeOperations receives status=401

### ISSUE THREAD

**Issue by KentaroWaki** [ecadlabs/taquito#2162]
**Description**
I just changed the tezos-node version to 15.0 and now forgeOperations receives status=401

**Steps To Reproduce**
await getRpcClient.forgeOperations(forgeParams);

**Expected behavior**
orgeOperations receives status=200

**Screenshots**
```
(node:16009) UnhandledPromiseRejectionWarning: HttpResponse: Http error response: (401) 
    at HttpBackend.<anonymous> (/home/ec2-user/tmp/node_modules/@taquito/http-utils/dist/taquito-http-utils.umd.js:480:31)
    at Generator.throw (<anonymous>)
    at rejected (/home/ec2-user/tmp/node_modules/@taquito/http-utils/dist/taquito-http-utils.umd.js:30:69)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Can I wait for taquito to support the Lima protocol?
When will it happen?

**Comment by KentaroWaki** [comment]
Sorry, my mistake, no problem for taquito.
