### ISSUE TITLE
InMemorySigner fails to sign encoded transaction

### ISSUE THREAD

**Issue by argjv** [ecadlabs/taquito#252]
The following code throws:
```
const signer = new InMemorySigner('spsk...');
const signedTransaction = await signer.sign(encodedTransaction, new Uint8Array([3]));
```

The error is:
```
TypeError: sodium.crypto_generichash is not a function
    at InMemorySigner.<anonymous> (node_modules/@taquito/signer/src/taquito-signer.ts:80:39)
    at step (node_modules/@taquito/signer/dist/taquito-signer.umd.js:58:27)
    at Object.next (node_modules/@taquito/signer/dist/taquito-signer.umd.js:39:57)
    at /Users/jorge/dev/bitgo-account-lib/node_modules/@taquito/signer/dist/taquito-signer.umd.js:32:75
    at new Promise (<anonymous>)
    at __awaiter (node_modules/@taquito/signer/dist/taquito-signer.umd.js:28:16)
    at InMemorySigner.sign (node_modules/@taquito/signer/dist/taquito-signer.umd.js:358:20)
```

After a quick search, I found out it is because the signer does not wait for `sodium` library to be ready.

This can be tested by calling the method `publicKeyHash()` which waits for the lib:

```
const signer = new InMemorySigner('spsk...');
const signerAddress = await signer.publicKeyHash();
const signedTransaction = await signer.sign(encodedTransaction, new Uint8Array([3]));
```

**Comment by jevonearth** [comment]
Thanks, Jorge.

I bumped into this issue in a different context, we will have a fix for this pretty soon.

**Comment by jevonearth** [comment]
Hi @argjv 

You can try out `6.0.3-beta.1` which should address this problem. Feedback welcome.

**Comment by jevonearth** [comment]
Closing, as I believe this is resolved. Please reach out if did not resolve your issue.
