### ISSUE TITLE
Unable to run integration-test against private rpc node with node v20 

### ISSUE THREAD

**Issue by hui-an-yang** [ecadlabs/taquito#2973]
When I tried to run integration-tests with node lts/iron -> v20.13.1 will get errors like below, lts/hydrogen -> v18.20.3 were fine.
Weirdly when i switch to public rpc url with the same node v20 were fine, might be a http and https differences.
I have back track to node v19.0.0 is when this behaviour started, will need to look into node release notes to find what need to be updated on taquito side. 

```
    Failed to originate ticket contract {"method":"GET","url":"http://ecad-oxfordnet-full.i.tez.ie:8732/chains/main/chain_id","cause":{"message":"request to http://ecad-oxfordnet-full.i.tez.ie:8732/chains/main/chain_id failed, reason: socket hang up","type":"system","errno":"ECONNRESET","code":"ECONNRESET"},"name":"HttpRequestFailed","message":"GET http://ecad-oxfordnet-full.i.tez.ie:8732/chains/main/chain_id FetchError: request to http://ecad-oxfordnet-full.i.tez.ie:8732/chains/main/chain_id failed, reason: socket hang up"}
```
and 
```
    HttpRequestFailed: GET http://ecad-ghostnet-rolling-2.i.tez.ie:8732/chains/main/chain_id FetchError: request to http://ecad-ghostnet-rolling-2.i.tez.ie:8732/chains/main/chain_id failed, reason: socket hang up
        at HttpBackend.<anonymous> (/Users/huianyang/ECAD_LABS/taquito/packages/taquito-http-utils/dist/taquito-http-utils.umd.js:504:31)
        at Generator.throw (<anonymous>)
        at rejected (/Users/huianyang/ECAD_LABS/taquito/packages/taquito-http-utils/dist/taquito-http-utils.umd.js:28:69)
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      method: 'GET',
      url: 'http://ecad-ghostnet-rolling-2.i.tez.ie:8732/chains/main/chain_id',
      cause: FetchError {
        message: 'request to http://ecad-ghostnet-rolling-2.i.tez.ie:8732/chains/main/chain_id failed, reason: socket hang up',
        type: 'system',
        errno: 'ECONNRESET',
        code: 'ECONNRESET'
      }
    }
```

**Comment by dsawali** [comment]
relevant issues:
- https://github.com/nodejs/node/issues/46287
- https://github.com/whatwg/fetch/issues/1631
