### ISSUE TITLE
Better handle block headers with no operations ([]) when originating contracts

### ISSUE THREAD

**Issue by CruzMolina** [ecadlabs/taquito#365]
[`confirmed$`](https://github.com/ecadlabs/taquito/blob/master/packages/taquito/src/operations/operations.ts#L79) assumes that all block headers will have an array of _some_ `operations`.

In the case where one is running a local private node and deploying a contract before interacting with it (no prior or previous tx's), an "empty" block can get polled and a contract `origination` call will fail.

i.e.

```
    TypeError: Cannot read property 'forEach' of undefined
        at MapSubscriber.project (/home/cruz/tezos-example-box/node_modules/@truffle/interface-adapter/node_modules/@taquito/taquito/src/operations/operations.ts:80:22)
        at MapSubscriber._next (/home/cruz/tezos-example-box/node_modules/rxjs/src/internal/operators/map.ts:84:29)
        at MapSubscriber.Subscriber.next (/home/cruz/tezos-example-box/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
        at SwitchMapSubscriber.notifyNext (/home/cruz/tezos-example-box/node_modules/rxjs/src/internal/operators/switchMap.ts:172:24)
        at InnerSubscriber._next (/home/cruz/tezos-example-box/node_modules/rxjs/src/internal/InnerSubscriber.ts:17:17)
        at InnerSubscriber.Subscriber.next (/home/cruz/tezos-example-box/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
        at /home/cruz/tezos-example-box/node_modules/rxjs/src/internal/util/subscribeToPromise.ts:8:20
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Note**: investigate whether this behaviour still occurs. Very possible that this has been fixed by previous tickets.

**Comment by dsawali** [comment]
Closing since this behaviour doesn't seem to occur anymore. Also a very uncommon use case.
