### ISSUE TITLE
InMemorySigner.sign not working

### ISSUE THREAD

**Issue by Sword-Smith** [ecadlabs/taquito#438]
When I call the `sign` function, I get an error. I have:
```
var signature = aliceSk.sign(msgToSign, undefined);
```

This throws this error:
```
Uncaught TypeError: hex.match is not a function
      at Object.hex2buf (node_modules/@taquito/utils/src/taquito-utils.ts:143:29)
      at InMemorySigner.hex2buf (node_modules/@taquito/signer/src/taquito-signer.ts:91:14)
      at step (node_modules/@taquito/signer/dist/taquito-signer.umd.js:59:27)
      at Object.next (node_modules/@taquito/signer/dist/taquito-signer.umd.js:40:57)
      at /home/thv/source/repos/ligo-tutorial/node_modules/@taquito/signer/dist/taquito-signer.umd.js:33:75
      at new Promise (<anonymous>)
      at __awaiter (node_modules/@taquito/signer/dist/taquito-signer.umd.js:29:16)
      at InMemorySigner.sign (node_modules/@taquito/signer/dist/taquito-signer.umd.js:427:20)
      at Context.it (test/payment_channel_tests/payment_channel_tests.js:47:37)
```

**Comment by Sword-Smith** [comment]
Problem: I called `sign` with an input of type `UInt8Array`. It should be a (hex) string instead.
