### ISSUE TITLE
Add a flextesa node to our CI pipeline

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#457]
Steps

1. Set up and document how to run the integration test suite against a local flextesa sandbox
   - Figure out a way to easily originate all well-known contracts into a fresh-sandbox (same task as required when adding a new protocol/testnet)
2. Integrate flextesa into the CI pipeline

Relates to #276

**Comment by michaelkernaghan** [comment]
Tezos Doc on Flexible Network Sandboxes.  https://tezos.gitlab.io/developer/flextesa.html

**Comment by michaelkernaghan** [comment]
I tried a few things

first, set up sandbox:  https://assets.tqtezos.com/docs/setup/2-sandbox/

then:  in integration-tests/package.json  add to scripts {
 "test:sandbox": "SANDBOX=true jest",

in integration-tests/config.ts add:

const sandboxEphemeral = {
  rpc: process.env['TEZOS_RPC_SANDBOX'] || 'http://localhost:20000',
  knownBaker: 'tz1R55a2HQbXUAzWKJYE5bJp3UvvawwCm9Pr',
  knownContract: 'KT1MTFjUeqBeZoFeW1NLSrzJdcS5apFiUXoB',
  knownBigMapContract: 'KT1Aqk5xE36Kx7JUUV8VMx4t9jLgQn4MBWQk',
  protocol: Protocols.PtEdo2Zk,
  signerConfig: {
    type: SignerType.EPHEMERAL_KEY as SignerType.EPHEMERAL_KEY,
    keyUrl: 'https://api.tez.ie/keys/edonet',
    requestHeaders: { 'Authorization': 'Bearer taquito-example' },
  }
}

if you run npm test:sandbox  with these changes you get 

Test Suites: 82 failed, 4 passed, 86 total
Tests:       174 failed, 129 skipped, 489 passed, 792 total

errors like this:
    Received: {"body": "[{\"kind\":\"branch\",\"id\":\"proto.008-PtEdo2Zk.implicit.empty_implicit_contract\",\"implicit\":\"tz3P5SzMy9W41KLuQvwTL64hCrckzxunSzvT\"}]
    ", "message": "Http error response: (500) [{\"kind\":\"branch\",\"id\":\"proto.008-PtEdo2Zk.implicit.empty_implicit_contract\",\"implicit\":\"tz3P5SzMy9W41KLuQvwTL64hCrckzxunSzvT\"}]
    ", "name": "HttpResponse", "status": 500, "statusText": "Internal Server Error", "url": "http://localhost:20000/chains/main/blocks/head/helpers/scripts/run_operation"}

this is keygen complaining
.
we will need to set up addresses and other assets on the sandbox for the tests to use 
for example, address have fund on testnet not in the sandbox
so it tries for example to deploy a contract with an empty account

but in principle, it should work this way

**Comment by michaelkernaghan** [comment]
I am going to start on a script in Taquito to do this:
Figure out a way to easily originate all well-known contracts into a fresh-sandbox (same task as required when adding a new protocol/testnet)

**Comment by michaelkernaghan** [comment]
I have attached a list of all the contracts that are used in the integration tests

[Contract-ids-used-in-integration-tests.txt](https://github.com/ecadlabs/taquito/files/6157573/Contract-ids-used-in-integration-tests.txt)

**Comment by roxaneletourneau** [comment]
@michaelkernaghan Yes, only the "know contracts" are required, the others are generated during the tests. The code to deploy the know contracts can be found here: https://github.com/ecadlabs/taquito/blob/c81a7bd496437c830f2428e55c53f3ba6e278c59/example/deploy-integration-tests-contracts.ts

**Comment by michaelkernaghan** [comment]
Steps:
1. Deploy flextesa sandbox onto a virtual machine and get the node running
     - done 
2. Run the deploy-integration-tests-contracts.ts script to populate the sandbox
     - script times out   2021-03-18
3. Run the integration tests with the required configuration and chase down errors
     -
4. Set the CI script to run the integration tests against the sandbox  (clone of edonet playbook)

**Comment by michaelkernaghan** [comment]
here is the Error when i run the taquito script to create bigmap assets on the sandbox on the VM:  

mike@halen:~/taquito/example$ node -r ts-node/register deploy-integration-tests-contracts.ts
Deploying the knownContract...
Awaiting confirmation...
Error: Confirmation polling timed out
    at TapSubscriber._tapNext (/home/mike/taquito/packages/taquito/src/operations/operations.ts:68:17)
    at TapSubscriber._next (/home/mike/taquito/packages/taquito/node_modules/rxjs/src/internal/operators/tap.ts:120:21)
    at TapSubscriber.Subscriber.next (/home/mike/taquito/packages/taquito/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at SwitchMapSubscriber.notifyNext (/home/mike/taquito/packages/taquito/node_modules/rxjs/src/internal/operators/switchMap.ts:166:24)
    at SimpleInnerSubscriber._next (/home/mike/taquito/packages/taquito/node_modules/rxjs/src/internal/innerSubscribe.ts:30:17)
    at SimpleInnerSubscriber.Subscriber.next (/home/mike/taquito/packages/taquito/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at MapToSubscriber._next (/home/mike/taquito/packages/taquito/node_modules/rxjs/src/internal/operators/mapTo.ts:70:22)
    at MapToSubscriber.Subscriber.next (/home/mike/taquito/packages/taquito/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at AsyncAction.dispatch (/home/mike/taquito/packages/taquito/node_modules/rxjs/src/internal/observable/timer.ts:91:14)
    at AsyncAction._execute (/home/mike/taquito/packages/taquito/node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:122:12)
/home/mike/taquito/packages/taquito/src/operations/operations.ts:68
          throw new Error(`Confirmation polling timed out`);
                ^
Error: Confirmation polling timed out
    at TapSubscriber._tapNext (/home/mike/taquito/packages/taquito/src/operations/operations.ts:68:17)
    at TapSubscriber._next (/home/mike/taquito/packages/taquito/node_modules/rxjs/src/internal/operators/tap.ts:120:21)
    at TapSubscriber.Subscriber.next (/home/mike/taquito/packages/taquito/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at SwitchMapSubscriber.notifyNext (/home/mike/taquito/packages/taquito/node_modules/rxjs/src/internal/operators/switchMap.ts:166:24)
    at SimpleInnerSubscriber._next (/home/mike/taquito/packages/taquito/node_modules/rxjs/src/internal/innerSubscribe.ts:30:17)
    at SimpleInnerSubscriber.Subscriber.next (/home/mike/taquito/packages/taquito/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at MapToSubscriber._next (/home/mike/taquito/packages/taquito/node_modules/rxjs/src/internal/operators/mapTo.ts:70:22)
    at MapToSubscriber.Subscriber.next (/home/mike/taquito/packages/taquito/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at AsyncAction.dispatch (/home/mike/taquito/packages/taquito/node_modules/rxjs/src/internal/observable/timer.ts:91:14)
    at AsyncAction._execute (/home/mike/taquito/packages/taquito/node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:122:12)

**Comment by michaelkernaghan** [comment]
We have lowered the polling time to no effect

`tezos.setProvider({config: {confirmationPollingIntervalSecond: 1}})`

**Comment by roxaneletourneau** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/457?planning-poker) with Zenhub @dsawali @hui-an-yang @zainen
