### ISSUE TITLE
Cannot import VIEW_LAMBDA to originate it on the sandbox

### ISSUE THREAD

**Issue by emishur** [ecadlabs/taquito#536]
Taquito version: 7.1.0-preview.8

How to reproduce:
1. create a new project and install taquito package from the npm repo:
   
  `npm i @taquito/taquito@7.1.0-preview.8`

2. Import `VIEW_LAMBDA` in your index.ts file:

`import { VIEW_LAMBDA } from '@taquito/taquito/dist/types/contract/view_lambda';`

and add code which references it. For instance `console.log(VIEW_LAMBDA.storage);`

3. run you project. You will get the following or similar error:

```
Error: Cannot find module '@taquito/taquito/dist/types/contract/view_lambda'
Require stack:
- /app/src/index.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
     at require (internal/modules/cjs/helpers.js:88:18)
     at Object.<anonymous> (/app/src/context.ts:5:1)
     at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (/app/node_modules/source-map-support/source-map-support.js:547:25)
     at Module.m._compile (/tmp/ts-node-dev-hook-4750696789248545.js:57:33)
     at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
     at require.extensions.<computed> (/tmp/ts-node-dev-hook-4750696789248545.js:59:20)
```

It looks like something is broken with the build of the distribution package

**Comment by roxaneletourneau** [comment]
Hi @emishur,
This issue should be fixed in 7.1.0-beta.0 
The import needs to be from @taquito/taquito:
`import { VIEW_LAMBDA } from '@taquito/taquito'`
