### ISSUE TITLE
 Taquito integration test tzip16-metadata-view.spec.ts fails frequently and should be made more resilient

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#650]
There are some Taquito integration tests that fail in CI more often than others and should be looked at to improve resiliency. Reducing the frequency of failures of these tests will enhance the CI process and avoid having to rerun jobs.
In this case, it is tzip16-metadata-view.spec.ts

**Steps To Reproduce**
1. Go to for example https://github.com/ecadlabs/taquito/pull/649/checks?check_run_id=1972654309
2. Review the integration run fails:  
3. observe "FAIL ./tzip16-metadata-view.spec.ts (47.183 s)" due to Bad Gateway 

full detail:
```
FAIL ./tzip16-metadata-view.spec.ts (47.183 s)
  ● Execute views example from TZComet: https://api.tez.ie/rpc/delphinet › Deploy a contract with metadata having a couple of views (example taken from TZComet) and call the views

    HttpResponse: Http error response: (502) 502 Bad Gateway

      60 | 		});
      61 | 
    > 62 | 		it('Deploy a contract with metadata having a couple of views (example taken from TZComet) and call the views', async (done) => {
         | 		^
      63 | 			// KT18tKt6ysL5QVqLMmwQL5p5Nu6m8KjRbhSb
      64 | 			const metadataBigMAp = new MichelsonMap();
      65 | 			metadataBigMAp.set("", char2Bytes('tezos-storage:here'));

      at new Spec (node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (tzip16-metadata-view.spec.ts:62:3)
```

**Expected behavior**
The test should not fail frequently due to connectivity issues. It should fail when there is a code regression that broke something in its code path.

**Comment by michaelkernaghan** [comment]
trying the jest rest npm package

**Comment by michaelkernaghan** [comment]
It seems to work.
I have done three files and in 5 runs none of them failed again.
It may be too soon but it's not bad news.

I will add retries to the following test and do 5 runs again:
  tzip16-originate-contracts-with-metadata-on-HTTPS-and-fetch-metadata.spec.ts 
  wallet-init-with-empty-bigmap.spec.ts
  contract-unit-as-param.spec.ts.
