### ISSUE TITLE
Frequent "Signature failed verification against public key" errors in CICD integration tests

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#848]
CICD Taquito integration tests will have intermittent but frequent failures that show the following stack trace:
```
121 |       const signatureVerified = await this.verify(watermarkedBytes, signature);
      122 |       if (!signatureVerified) {
    > 123 |         throw new Error(
          |               ^
      124 |           `Signature failed verification against public key:
      125 |           {
      126 |             bytes: ${watermarkedBytes},
      at RemoteSigner.<anonymous> (../packages/taquito-remote-signer/src/taquito-remote-signer.ts:123:15)
      at step (../packages/taquito-remote-signer/dist/taquito-remote-signer.umd.js:60:27)
      at Object.next (../packages/taquito-remote-signer/dist/taquito-remote-signer.umd.js:41:57)
      at fulfilled (../packages/taquito-remote-signer/dist/taquito-remote-signer.umd.js:31:62)
```
there are various tests that can fail with this exception at one time or another. 

It would be good to know why this is happening and to mitigate it to improve CICD flow reliability.

1. There are frequent examples I the test fail logs for integration tests in CICD

**Expected behavior**
The operation that is failing in these tests should be available in a reliable way and not be subject to intermittent failure in the CICD test environment. A code solution, or an environmental solution, is needed to mitigate these intermittent failures.

**Comment by michaelkernaghan** [comment]
Here is a full FAIL message:
```
FAIL ./batch-api.spec.ts (151.129 s)
  ● Test batch api using: *** › Test batch from account with low balance

    Signature failed verification against public key:
              {
                bytes: 038fb58864f507519e4ea58d78708c99110942b515da6bdaccac7fe2378e60d95d6b023f5b98d1b5aa753abce285b5d10a6aafad72d1e18c0ba0af2de8520002026dc6730077aff62474632e5b2625a43341539d585e553e547a7dbb313b8dd7f86c023f5b98d1b5aa753abce285b5d10a6aafad72d1e1fb03a1af2df70b810280897a0002e34c8b6b18bd7f72d148c7e33255bd2401eab2a400,
                signature: p2sigXejNaP3SWoeq7ieJSrYuPqoUiwXhf9SrLsHXhdYKb8YzH694EqRjRJY5krLHC692tD3wU8ymBmKsdBxopZoW9GEoTpydN
              }

      121 |       const signatureVerified = await this.verify(watermarkedBytes, signature);
      122 |       if (!signatureVerified) {
    > 123 |         throw new Error(
          |               ^
      124 |           `Signature failed verification against public key:
      125 |           {
      126 |             bytes: ${watermarkedBytes},

      at RemoteSigner.<anonymous> (../packages/taquito-remote-signer/src/taquito-remote-signer.ts:123:15)
      at step (../packages/taquito-remote-signer/dist/taquito-remote-signer.umd.js:60:27)
      at Object.next (../packages/taquito-remote-signer/dist/taquito-remote-signer.umd.js:41:57)
      at fulfilled (../packages/taquito-remote-signer/dist/taquito-remote-signer.umd.js:31:62)
```

**Comment by jevonearth** [comment]
@michaelkernaghan next time this happens, can you find the corresponding logs for the key-gen service (via our Grafana/Loki)

**Comment by michaelkernaghan** [comment]
A grafana chart for the time period prior to an example of the failure is here:
https://monitoring.tez.ie/grafana/d/R48EUusWz/faucet-key-api?from=1620416100000&to=16204166650000

the CICD does not timestamp each FAIL so it's in a range prior to the date stamp on the CICD run log.
