### ISSUE TITLE
Schema.ExecuteOnBigMapValue() fails on a ticket

### ISSUE THREAD

**Issue by psmolinsky** [ecadlabs/taquito#970]
**Description**

The method `ExecuteOnBigMapValue()` or `Schema` fails to deserialize a Michelson with a ticket as it is present in a blockchain. Same applies for `Execute()` with a partial schema.

**Steps To Reproduce**
1. Run this code:
    ```typescript
    const schema = new Schema({
        prim: 'big_map',
        args: [{ prim: 'nat' }, { prim: 'ticket', args: [{ prim: 'nat' }] }],
        annots: ['%tickets']
        });
    const value = schema.ExecuteOnBigMapValue({
        prim: 'Pair',
        args: [
            { string: 'KT1EAMUQC1yJ2sRPNPpLHVMGCzroYGe1C1ea' },
            {
                prim: 'Pair',
                args: [{ int: '0' }, { int: '1' }],
            },
        ],
    });
    ```
2. It throws following error:
    ```
    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)
        at IntToken.Execute (...\node_modules\@taquito\michelson-encoder\src\tokens\comparable\int.ts:23:37)
        at TicketToken.Execute (...\node_modules\@taquito\michelson-encoder\src\tokens\ticket.ts:42:22)
        at Schema.ExecuteOnBigMapValue (...\node_modules\@taquito\michelson-encoder\src\schema\storage.ts:139:36)
    ```

**Expected behavior**
It should deserialize the value correctly.

**Additional context**
You have [a corresponding test](https://github.com/ecadlabs/taquito/blob/master/packages/taquito-michelson-encoder/test/sample18_nat_ticket.spec.ts#L43-L55) with [the test data](https://github.com/ecadlabs/taquito/blob/master/packages/taquito-michelson-encoder/data/sample18_ticket.ts#L491-L494) for this case. It passes because the test data are flattened in a single pair's `args`. However this is not the case for real data on the blockchain e.g. contract `KT1CnygLoKfJA66499U9ZQkL6ykUfzgruGfM` or `KT1GGfcjjDMfxwAwZFYhPvxgmR4GpitVmEto`.

**Comment by mbodecek** [comment]
Just to add to @psmolinsky, here the code seems to rely on the optimized (Edo) notation. We believe both the full and the optimized notation should probably be supported.

**Comment by kjaiswal** [comment]
Hi @psmolinsky ,

I would like to know the source of data you use in sample code above. I tried the contracts KT1CnygLoKfJA66499U9ZQkL6ykUfzgruGfM and KT1GGfcjjDMfxwAwZFYhPvxgmR4GpitVmEto but I see flattened structures there as well. See -

https://api.tez.ie/rpc/mainnet/chains/main/blocks/head/context/big_maps/5696/expru28t4XoyB61WuRQnExk3Kq8ssGv1ejgdo9XHxpTXoQjXTGw1Dg

and

https://api.tez.ie/rpc/florencenet/chains/main/blocks/head/context/big_maps/43436/expruTsjYd9fsDpMydp2E7jSTfBwVH92RPazTKVjpNtgqNjZBMa2sM

Thanks,

Kunal

**Comment by mbodecek** [comment]
Hi @kjaiswal thanks for looking into this!

Looks like the full notation is still used in big map diffs. For example here: https://api.tez.ie/rpc/mainnet/chains/main/blocks/1576567

Full snippet:
```
                    "lazy_storage_diff": [
                      {
                        "kind": "big_map",
                        "id": "5696",
                        "diff": {
                          "action": "update",
                          "updates": [
                            {
                              "key_hash": "exprv3jzjc26YvioGD7AGq3isK8Mzo4xQ3pcxLGnHkLXn7ibrAP8Fv",
                              "key": {
                                "prim": "Pair",
                                "args": [
                                  {
                                    "bytes": "00000766aae676494cecd5cda822679eb6059e1a3558"
                                  },
                                  {
                                    "string": "standard"
                                  }
                                ]
                              },
                              "value": {
                                "prim": "Pair",
                                "args": [
                                  {
                                    "int": "1627461042"
                                  },
                                  {
                                    "prim": "Pair",
                                    "args": [
                                      {
                                        "bytes": "012e2f9b3ed43b73564c4b3dab30c8531f0e2c159100"
                                      },
                                      {
                                        "prim": "Pair",
                                        "args": [
                                          {
                                            "string": "standard"
                                          },
                                          {
                                            "int": "3"
                                          }
                                        ]
                                      }
                                    ]
                                  }
                                ]
                              }
                            }
                          ]

```
